name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      os:
        - ubuntu-latest
        - macos-latest
        - windows-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 12
          cache: yarn
      - run: yarn install --frozen-lockfile
      - name: Build
        run: yarn build

  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 12
          cache: yarn
      - run: yarn install --frozen-lockfile
      - name: Test and Generate Coverage
        run: yarn test:coverage
      - name: Upload Coverage
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
      - uses: ./
        id: output-step
        with:
          variables: |
            FOO=BAR
            HELLO=$(echo WORLD)
            QUOTES=$(echo 'quoted')
            WORD_COUNT=$(echo 'foo bar' | wc -w)
      - name: Check FOO
        run: |
          echo "FOO is '${{ steps.output-step.outputs.FOO }}'"
          exit 1
        if: ${{ steps.output-step.outputs.FOO != 'BAR' }}
      - name: Check HELLO
        run: |
          echo "HELLO is '${{ steps.output-step.outputs.HELLO }}'"
          exit 1
        if: ${{ steps.output-step.outputs.HELLO != 'WORLD' }}
      - name: Check QUOTES
        run: |
          echo "QUOTES is '${{ steps.output-step.outputs.QUOTES }}'"
          exit 1
        if: ${{ steps.output-step.outputs.QUOTES != 'quoted' }}
      - name: Check WORD_COUNT
        run: |
          echo "WORD_COUNT is '${{ steps.output-step.outputs.WORD_COUNT }}'"
          exit 1
        if: ${{ steps.output-step.outputs.WORD_COUNT != '2' }}
